apiVersion: v1
kind: Service
metadata:
  name: contact-delete-service
spec:
  type: NodePort # Apenas acessível dentro do cluster
  selector:
    app: contact-delete
  ports:
    - protocol: TCP
      port: 80          # Porta do Service
      targetPort: 8080  # Porta do container
      nodePort: 30002