apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-delete-deployment
  labels:
    app: contact-delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-delete
  template:
    metadata:
      labels:
        app: contact-delete
    spec:
      containers:
        - name: contact-delete-ms
          image: oh20/contactmicroservice-delete:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: rabbitmq-connection
          volumeMounts:
          - name: shared-storage
            mountPath: /usr/share/volume
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc