apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-create-deployment
  labels:
    app: contact-create
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-create
  template:
    metadata:
      labels:
        app: contact-create
    spec:
      containers:
        - name: contact-create-ms
          image: oh20/contactmicroservice-create:v1
          ports:
            - containerPort: 8080
