apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-query-deployment
  labels:
    app: contact-query
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-query
  template:
    metadata:
      labels:
        app: contact-query
    spec:
      containers:
        - name: contact-query-ms
          image: oh20/contactmicroservice-query:latest
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: shared-storage
            mountPath: /usr/share/volume
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc