apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672 # Porta padrão do RabbitMQ para conexões AMQP
            - containerPort: 15672 # Porta do painel de gerenciamento
          envFrom:
            - configMapRef:
                name: rabbitmq-config