apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp-port # Nome para a porta AMQP
      protocol: TCP
      port: 5672       # Porta padrão AMQP
      targetPort: 5672 # Porta no container
      nodePort: 32000  # Porta externa para AMQP
    - name: management-port # Nome para o painel de gerenciamento
      protocol: TCP
      port: 15672       # Porta do painel de gerenciamento
      targetPort: 15672 # Porta no container
      nodePort: 32001   # Porta externa para o painel de gerenciamento
