apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-dbapi-deployment
  labels:
    app: contact-dbapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-dbapi
  template:
    metadata:
      labels:
        app: contact-dbapi
    spec:
      containers:
        - name: contact-dbapi-ms
          image: oh20/contactmicroservice-dbconsumer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: rabbitmq-connection-api
          volumeMounts:
          - name: shared-storage
            mountPath: /usr/share/volume
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc